### PR TITLE
Services cloudapi

### PR DESCRIPTION
**Pull request by namtzigla**
Hi,

this is a small PR that add ListServices()

### CODE REVIEW

**Comment by BrianHicks** [comment]
Hi @mantzigla! This looks great so far, could you please add some tests and an appropriate line in the README for what this does? Thanks!

**Comment by misterbisson** [comment]
@namtzigla Did you see @BrianHicks' question earlier? This looks like a great addition, but can you add some tests and update the readme to document it?

**Comment by namtzigla** [comment]
@misterbisson @BrianHicks, sorry guys but I didn't had time to work on this lately, I will close the PR next week if I can't finish it.

**Comment by namtzigla** [comment]
@misterbisson @BrianHicks I've added a small test for this. On the side note I've run into a problem with the new updates from gocommon so I had to change the logger, so please check https://github.com/namtzigla/gosdc/blob/master/cloudapi/cloudapi.go#L65

thanks

**Comment by namtzigla** [comment]
@misterbisson @BrianHicks I've added a small test for ListServices. Let me know if you feel it need 

thanks

**Comment by BrianHicks** [comment]
LGTM! Thanks.

**Pull request merged**
